// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAV4F5ScLOhvmuXO9c1GEofdL1DGL4S8A',
    appId: '1:412174503644:web:663999e0cfcd72640bae19',
    messagingSenderId: '412174503644',
    projectId: 'projectmoblie1',
    authDomain: 'projectmoblie1.firebaseapp.com',
    storageBucket: 'projectmoblie1.appspot.com',
    measurementId: 'G-VH7XPKEQ20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHBkY_RfXHmXEZb0b_TQRhUjH2J4f5XUI',
    appId: '1:412174503644:android:ba9eb0494de76a230bae19',
    messagingSenderId: '412174503644',
    projectId: 'projectmoblie1',
    storageBucket: 'projectmoblie1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZPORR5j1c5CQPmZ3hjrP58Zi0XUfAzts',
    appId: '1:412174503644:ios:ca42b61c29bb4dd10bae19',
    messagingSenderId: '412174503644',
    projectId: 'projectmoblie1',
    storageBucket: 'projectmoblie1.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZPORR5j1c5CQPmZ3hjrP58Zi0XUfAzts',
    appId: '1:412174503644:ios:ca42b61c29bb4dd10bae19',
    messagingSenderId: '412174503644',
    projectId: 'projectmoblie1',
    storageBucket: 'projectmoblie1.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAV4F5ScLOhvmuXO9c1GEofdL1DGL4S8A',
    appId: '1:412174503644:web:c2cda1a4a1ae823f0bae19',
    messagingSenderId: '412174503644',
    projectId: 'projectmoblie1',
    authDomain: 'projectmoblie1.firebaseapp.com',
    storageBucket: 'projectmoblie1.appspot.com',
    measurementId: 'G-40G3W3PREL',
  );
}
